server:
  port: 8082
spring:
  application:
    name: seat-service
  datasource:
    url: jdbc:mysql://localhost:3306/seat_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
services:
  passenger-url: http://localhost:8083/api/passengers
  notification-url: http://localhost:8089/notifications
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
